// <auto-generated />
using System;
using HabitTrackerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTrackerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251005104146_SqliteMigration")]
    partial class SqliteMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("HabitTrackerApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.DailyHabitEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reflection")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("DailyHabitEntries");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.DailyMetricValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyHabitEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HabitMetricDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("REAL");

                    b.Property<string>("TextValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DailyHabitEntryId");

                    b.HasIndex("HabitMetricDefinitionId");

                    b.ToTable("DailyMetricValues");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonthlyDays")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecurrenceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SpecificDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TimeOfDay")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TimeOfDayEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklyDays")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.HabitMetricDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.ToTable("HabitMetricDefinitions");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.DailyHabitEntry", b =>
                {
                    b.HasOne("HabitTrackerApp.Models.Habit", "Habit")
                        .WithMany("DailyHabitEntries")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.DailyMetricValue", b =>
                {
                    b.HasOne("HabitTrackerApp.Models.DailyHabitEntry", "DailyHabitEntry")
                        .WithMany("DailyMetricValues")
                        .HasForeignKey("DailyHabitEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HabitTrackerApp.Models.HabitMetricDefinition", "HabitMetricDefinition")
                        .WithMany()
                        .HasForeignKey("HabitMetricDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DailyHabitEntry");

                    b.Navigation("HabitMetricDefinition");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.Habit", b =>
                {
                    b.HasOne("HabitTrackerApp.Models.Category", "Category")
                        .WithMany("Habits")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.HabitMetricDefinition", b =>
                {
                    b.HasOne("HabitTrackerApp.Models.Habit", "Habit")
                        .WithMany()
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.Category", b =>
                {
                    b.Navigation("Habits");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.DailyHabitEntry", b =>
                {
                    b.Navigation("DailyMetricValues");
                });

            modelBuilder.Entity("HabitTrackerApp.Models.Habit", b =>
                {
                    b.Navigation("DailyHabitEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
